<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@yield('title', 'SYNAPSE document')</title>
    <style>
        @page { margin: 28px 34px 70px 34px; }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            color: #0f172a;
            margin: 0;
        }

        .header { border-bottom: 2px solid {{ $primary_color }}; padding-bottom: 10px; }
        .header td { vertical-align: middle; }
        .logo { width: 62px; height: 62px; object-fit: contain; }
        .school-name { font-size: 17px; font-weight: bold; color: {{ $primary_color }}; }
        .school-meta { font-size: 9.5px; color: #475569; line-height: 1.5; }
        .motto { font-style: italic; font-size: 9.5px; color: #64748b; }

        .doc-title {
            margin: 18px 0 4px 0;
            text-align: center;
            font-size: 14px;
            font-weight: bold;
            letter-spacing: 1.4px;
            text-transform: uppercase;
        }
        .doc-subtitle { text-align: center; font-size: 10px; color: #64748b; margin-bottom: 14px; }

        table { width: 100%; border-collapse: collapse; }
        table.data th {
            background: #f1f5f9;
            border: 1px solid #cbd5e1;
            padding: 6px 7px;
            font-size: 9.5px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
            text-align: left;
        }
        table.data td { border: 1px solid #cbd5e1; padding: 6px 7px; }
        table.data tr:nth-child(even) td { background: #f8fafc; }
        .num { text-align: right; }
        .center { text-align: center; }
        .muted { color: #64748b; }
        .bold { font-weight: bold; }

        .panel { border: 1px solid #e2e8f0; background: #f8fafc; padding: 9px 11px; }
        .panel td { padding: 2px 0; font-size: 10.5px; }
        .label { color: #64748b; width: 34%; }

        .summary { margin-top: 14px; }
        .summary .cell {
            border: 1px solid #e2e8f0;
            padding: 8px 10px;
            text-align: center;
        }
        .summary .cell .value { font-size: 15px; font-weight: bold; color: {{ $primary_color }}; }
        .summary .cell .caption { font-size: 8.5px; text-transform: uppercase; color: #64748b; letter-spacing: 0.5px; }

        .signature { margin-top: 34px; }
        .signature td { width: 50%; font-size: 10px; padding-top: 34px; }
        .signature .line { border-top: 1px solid #94a3b8; padding-top: 4px; width: 62%; }

        footer {
            position: fixed;
            left: 0; right: 0; bottom: -46px;
            height: 54px;
            font-size: 8px;
            color: #64748b;
            border-top: 1px solid #e2e8f0;
            padding-top: 6px;
        }
        .verify { font-family: 'DejaVu Sans Mono', monospace; color: #0f172a; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            @if ($logo)
                <td style="width: 74px;"><img src="{{ $logo }}" class="logo" alt=""></td>
            @endif
            <td>
                <div class="school-name">{{ $school_name }}</div>
                <div class="school-meta">
                    @if ($school_address){{ $school_address }}<br>@endif
                    @if ($school_phone)Tel: {{ $school_phone }}@endif
                    @if ($school_email) · {{ $school_email }}@endif
                </div>
                @if ($motto)<div class="motto">“{{ $motto }}”</div>@endif
            </td>
            <td style="width: 150px; text-align: right;" class="school-meta">
                Issued {{ $issued_at->format('d M Y') }}<br>
                @if (! empty($reference))Ref: <span class="verify">{{ $reference }}</span>@endif
            </td>
        </tr>
    </table>

    @yield('content')

    <footer>
        Generated by SYNAPSE for {{ $school_name }} on {{ $issued_at->format('d M Y H:i') }}.
        @if (! empty($verification_code))
            <br>Verify this document at {{ $verification_url }} — code <span class="verify">{{ $verification_code }}</span>.
        @endif
        <br>This document is issued electronically and is valid without a handwritten signature unless stated otherwise.
    </footer>
</body>
</html>
